import { sessionDuration } from './jsonl'
import { computeSessionStats } from '../analytics/sessionStats'
import type { TraceSession } from '../types'

function esc(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function sessionToHtml(session: TraceSession): string {
  const stats = computeSessionStats(session)
  const total = sessionDuration(session) || 1
  const spans = [...session.spans].sort((a, b) => a.startMs - b.startMs)

  const kindRows = Object.entries(stats.byKind)
    .map(
      ([kind, v]) =>
        `<tr><td>${esc(kind)}</td><td>${v!.count}</td><td>${v!.durationMs}</td></tr>`,
    )
    .join('')

  const spanRows = spans
    .map((span) => {
      const d = span.endMs - span.startMs
      const pct = ((d / total) * 100).toFixed(1)
      const err = span.error
        ? `<div class="err">${esc(span.error)}</div>`
        : ''
      return `<tr class="${span.status === 'error' ? 'err-row' : ''}">
        <td>${span.startMs}–${span.endMs}ms</td>
        <td><code>${esc(span.name)}</code>${err}</td>
        <td>${esc(span.kind)}</td>
        <td>${esc(span.status)}</td>
        <td>${d}ms (${pct}%)</td>
      </tr>`
    })
    .join('')

  const chunks = session.spans.flatMap((s) => s.ragChunks ?? [])
  const evidence = chunks
    .map(
      (c, i) =>
        `<article><h3>[${i + 1}] ${esc(c.source)} · ${c.score}</h3><p>${esc(c.text)}</p></article>`,
    )
    .join('')

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"/>
<title>OpenTrace · ${esc(session.title)}</title>
<style>
  body{font-family:system-ui,sans-serif;max-width:920px;margin:2rem auto;padding:0 1rem;color:#122;line-height:1.5;background:#f7faf8}
  h1{font-size:1.35rem} h2{font-size:1.05rem;margin-top:1.6rem;border-bottom:1px solid #cde;padding-bottom:.3rem}
  table{width:100%;border-collapse:collapse;font-size:.9rem} th,td{border:1px solid #c5d5cc;padding:.4rem .5rem;text-align:left;vertical-align:top}
  th{background:#e8f2ec} .err-row{background:#ffe8e8} .err{color:#b00020;font-size:.8rem;margin-top:.25rem}
  code{font-family:ui-monospace,monospace;font-size:.85em} .meta{color:#456;font-size:.9rem}
  article{border:1px solid #c5d5cc;border-radius:8px;padding:.7rem;margin:.5rem 0;background:#fff}
  footer{margin-top:2rem;color:#678;font-size:.8rem}
</style>
</head>
<body>
  <h1>OpenTrace Report · ${esc(session.title)}</h1>
  <p class="meta">
    ID <code>${esc(session.id)}</code> ·
    ${esc(session.startedAt)} ·
    ${stats.durationMs}ms ·
    spans ${stats.spanCount} (ok ${stats.okCount} / error ${stats.errorCount}) ·
    tokens ${stats.tokensIn}/${stats.tokensOut} ·
    est ~$${stats.estCostUsd.toFixed(4)}
    ${session.model ? ` · model <code>${esc(session.model)}</code>` : ''}
  </p>
  ${session.note ? `<h2>Note</h2><p>${esc(session.note)}</p>` : ''}
  <h2>Question</h2>
  <p>${esc(session.question || '—')}</p>
  <h2>Answer</h2>
  <p>${esc(session.answer || '—')}</p>
  <h2>Kind breakdown</h2>
  <table><thead><tr><th>Kind</th><th>Count</th><th>Duration (ms)</th></tr></thead><tbody>${kindRows}</tbody></table>
  <h2>Spans</h2>
  <table><thead><tr><th>Time</th><th>Name</th><th>Kind</th><th>Status</th><th>Duration</th></tr></thead><tbody>${spanRows}</tbody></table>
  ${chunks.length ? `<h2>RAG Evidence</h2>${evidence}` : ''}
  <footer>Generated by OpenTrace Studio</footer>
</body>
</html>`
}
