import { sessionDuration } from './jsonl'
import { computeSessionStats } from '../analytics/sessionStats'
import { buildRagSnapshot, ragSnapshotToMarkdown } from '../analytics/ragSnapshot'
import type { TraceSession } from '../types'

export function sessionToMarkdown(session: TraceSession): string {
  const stats = computeSessionStats(session)
  const lines: string[] = [
    `# OpenTrace Report · ${session.title}`,
    '',
    `- **Session ID:** \`${session.id}\``,
    `- **Started:** ${session.startedAt}`,
    `- **Duration:** ${stats.durationMs}ms`,
    `- **Spans:** ${stats.spanCount}（ok ${stats.okCount} / error ${stats.errorCount}）`,
    `- **Tokens:** in ${stats.tokensIn} · out ${stats.tokensOut}`,
    `- **Est. cost:** ~$${stats.estCostUsd.toFixed(4)} (approx.)`,
    session.model ? `- **Model:** \`${session.model}\`` : '',
    '',
    ...(session.note ? ['## Note', '', session.note, ''] : []),
    '## Question',
    '',
    session.question || '—',
    '',
    '## Answer',
    '',
    session.answer || '—',
    '',
    '## Kind breakdown',
    '',
    '| Kind | Count | Duration (ms) |',
    '|---|---:|---:|',
  ]

  for (const [kind, v] of Object.entries(stats.byKind)) {
    if (!v) continue
    lines.push(`| ${kind} | ${v.count} | ${v.durationMs} |`)
  }

  lines.push(
    '',
    '## Spans',
    '',
    '| Time | Name | Kind | Status | Duration |',
    '|---|---|---|---|---:|',
  )

  const total = sessionDuration(session) || 1
  for (const span of [...session.spans].sort((a, b) => a.startMs - b.startMs)) {
    const d = span.endMs - span.startMs
    const pct = ((d / total) * 100).toFixed(1)
    lines.push(
      `| ${span.startMs}–${span.endMs}ms | \`${span.name}\` | ${span.kind} | ${span.status} | ${d}ms (${pct}%) |`,
    )
    if (span.error) {
      lines.push(`| | *error:* ${escapeMd(span.error)} | | | |`)
    }
  }

  const chunks = session.spans.flatMap((s) =>
    (s.ragChunks ?? []).map((c) => ({ span: s.name, ...c })),
  )
  if (chunks.length) {
    lines.push('', '## RAG Evidence', '')
    chunks.forEach((c, i) => {
      lines.push(`### [${i + 1}] ${c.source} · score ${c.score}`)
      lines.push('')
      lines.push(c.text)
      lines.push('')
    })
  }

  const snap = buildRagSnapshot(session)
  if (snap.chunkCount > 0 || snap.retrieverSpans > 0) {
    lines.push(
      '',
      ragSnapshotToMarkdown(snap, { includeFooter: false }).replace(/^# /, '## ').trimEnd(),
      '',
    )
  }

  lines.push('', '---', '', '_Generated by OpenTrace Studio_', '')
  return lines.join('\n')
}

function escapeMd(s: string) {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}
