import { describe, expect, it } from 'vitest'
import { parseJsonl, eventsToSessions } from '../adapter/jsonl'
import {
  buildRagSnapshot,
  parseCitationIndexes,
  ragSnapshotToMarkdown,
} from './ragSnapshot'
import type { TraceSession } from '../types'

const OFFLINE = `{"type":"session","session":{"id":"offline-demo-1","title":"Offline","startedAt":"2026-09-03T00:00:00.000Z","question":"静安寺带娃？","answer":"合适 [1][2]。"}}
{"type":"span","span":{"sessionId":"offline-demo-1","id":"retrieve","name":"retriever.local_kb","kind":"retriever","status":"ok","startMs":95,"endMs":110,"ragChunks":[{"id":"c1","source":"kb/a.md","score":0.91,"text":"a"},{"id":"c2","source":"kb/b.md","score":0.2,"text":"b"}]}}
`

describe('ragSnapshot', () => {
  it('parses citation indexes', () => {
    expect(parseCitationIndexes('见 [1] 与 [2][2]')).toEqual([1, 2])
    expect(parseCitationIndexes('无引用')).toEqual([])
  })

  it('builds snapshot from offline-like session', () => {
    const session = eventsToSessions(parseJsonl(OFFLINE))[0]
    const snap = buildRagSnapshot(session)
    expect(snap.retrieverSpans).toBe(1)
    expect(snap.chunkCount).toBe(2)
    expect(snap.citationChunkCount).toBe(2)
    expect(snap.minScore).toBe(0.2)
    expect(snap.maxScore).toBe(0.91)
    expect(snap.lowScoreChunks).toHaveLength(1)
    expect(snap.lowScoreChunks[0].id).toBe('c2')
    expect(snap.citedIds).toEqual(['c1', 'c2'])
    expect(snap.uncitedChunkIds).toEqual([])
    expect(snap.answerHasCitation).toBe(true)
  })

  it('maps [n] to the last retriever span chunks', () => {
    const session: TraceSession = {
      id: 's',
      title: 't',
      startedAt: '2026-01-01T00:00:00.000Z',
      question: 'q',
      answer: '用 [1]',
      spans: [
        {
          id: 'r1',
          name: 'retriever.first',
          kind: 'retriever',
          status: 'ok',
          startMs: 0,
          endMs: 10,
          ragChunks: [{ id: 'old', source: 'a', score: 0.9, text: 'old' }],
        },
        {
          id: 'r2',
          name: 'retriever.last',
          kind: 'retriever',
          status: 'ok',
          startMs: 20,
          endMs: 30,
          ragChunks: [
            { id: 'new1', source: 'b', score: 0.8, text: 'n1' },
            { id: 'new2', source: 'c', score: 0.1, text: 'n2' },
          ],
        },
      ],
    }
    const snap = buildRagSnapshot(session)
    expect(snap.chunkCount).toBe(3)
    expect(snap.citationChunkCount).toBe(2)
    expect(snap.citedIds).toEqual(['new1'])
    expect(snap.uncitedChunkIds).toEqual(['new2'])
  })

  it('marks uncited when answer has fewer citations', () => {
    const session = eventsToSessions(parseJsonl(OFFLINE))[0]
    session.answer = '只引了第一段 [1]'
    const snap = buildRagSnapshot(session)
    expect(snap.citedIds).toEqual(['c1'])
    expect(snap.uncitedChunkIds).toEqual(['c2'])
  })

  it('renders markdown with optional footer', () => {
    const session = eventsToSessions(parseJsonl(OFFLINE))[0]
    const withFooter = ragSnapshotToMarkdown(buildRagSnapshot(session))
    expect(withFooter).toContain('RAG 质检快照')
    expect(withFooter).toContain('last retriever')
    expect(withFooter).toContain('_Generated by OpenTrace Studio_')
    const embedded = ragSnapshotToMarkdown(buildRagSnapshot(session), { includeFooter: false })
    expect(embedded).not.toContain('_Generated by OpenTrace Studio_')
  })
})
