import type { RagChunk, TraceSession } from '../types'

const LOW_SCORE = 0.35

export interface RagSnapshot {
  sessionId: string
  question: string
  retrieverSpans: number
  chunkCount: number
  /** Chunks used to resolve [n] citations (last retriever span). */
  citationChunkCount: number
  minScore: number | null
  maxScore: number | null
  lowScoreChunks: { id: string; source: string; score: number }[]
  citedIds: string[]
  uncitedChunkIds: string[]
  answerHasCitation: boolean
}

/** Parse [1][2] style citations from answer text (1-based index). */
export function parseCitationIndexes(answer: string | undefined): number[] {
  if (!answer) return []
  const out: number[] = []
  const re = /\[(\d+)\]/g
  let m: RegExpExecArray | null
  while ((m = re.exec(answer))) {
    const n = Number(m[1])
    if (Number.isFinite(n) && n >= 1) out.push(n)
  }
  return [...new Set(out)]
}

export function flattenRagChunks(session: TraceSession): (RagChunk & { spanName: string })[] {
  const out: (RagChunk & { spanName: string })[] = []
  for (const span of session.spans) {
    for (const c of span.ragChunks ?? []) {
      out.push({ ...c, spanName: span.name })
    }
  }
  return out
}

/** Prefer the last retriever span's chunks for [n] mapping (matches Live Run answer convention). */
export function citationChunksForSession(session: TraceSession): RagChunk[] {
  const retrievers = session.spans.filter((s) => s.kind === 'retriever')
  for (let i = retrievers.length - 1; i >= 0; i -= 1) {
    const chunks = retrievers[i].ragChunks
    if (chunks?.length) return chunks
  }
  return flattenRagChunks(session)
}

export function buildRagSnapshot(session: TraceSession): RagSnapshot {
  const retrievers = session.spans.filter((s) => s.kind === 'retriever')
  const chunks = flattenRagChunks(session)
  const citationChunks = citationChunksForSession(session)
  const scores = chunks.map((c) => Number(c.score)).filter((n) => Number.isFinite(n))
  const minScore = scores.length ? Math.min(...scores) : null
  const maxScore = scores.length ? Math.max(...scores) : null
  const lowScoreChunks = chunks
    .filter((c) => Number(c.score) < LOW_SCORE)
    .map((c) => ({ id: c.id, source: c.source, score: Number(c.score) }))

  const indexes = parseCitationIndexes(session.answer)
  const citedIds = indexes
    .map((i) => citationChunks[i - 1]?.id)
    .filter((id): id is string => Boolean(id))
  const citedSet = new Set(citedIds)
  const uncitedChunkIds = citationChunks.map((c) => c.id).filter((id) => !citedSet.has(id))

  return {
    sessionId: session.id,
    question: session.question,
    retrieverSpans: retrievers.length,
    chunkCount: chunks.length,
    citationChunkCount: citationChunks.length,
    minScore,
    maxScore,
    lowScoreChunks,
    citedIds: [...new Set(citedIds)],
    uncitedChunkIds,
    answerHasCitation: indexes.length > 0,
  }
}

export function ragSnapshotToMarkdown(
  s: RagSnapshot,
  opts?: { includeFooter?: boolean },
): string {
  const includeFooter = opts?.includeFooter !== false
  const lines = [
    `# RAG 质检快照 · ${s.sessionId}`,
    '',
    `- **Question:** ${s.question || '—'}`,
    `- **Retriever spans:** ${s.retrieverSpans}`,
    `- **Chunks (all / citation basis):** ${s.chunkCount} / ${s.citationChunkCount}`,
    `- **Citation rule:** \`[n]\` maps to the **last retriever** span's chunks (1-based)`,
    `- **Score range:** ${s.minScore === null ? '—' : s.minScore.toFixed(2)} – ${s.maxScore === null ? '—' : s.maxScore.toFixed(2)}`,
    `- **Answer has [n] citations:** ${s.answerHasCitation ? 'yes' : 'no'}`,
    `- **Cited chunk ids:** ${s.citedIds.length ? s.citedIds.join(', ') : '—'}`,
    `- **Uncited chunk ids (citation basis):** ${s.uncitedChunkIds.length ? s.uncitedChunkIds.join(', ') : '—'}`,
    '',
  ]
  if (s.lowScoreChunks.length) {
    lines.push('## Low-score chunks (< 0.35)', '')
    for (const c of s.lowScoreChunks) {
      lines.push(`- \`${c.id}\` · ${c.source} · ${c.score.toFixed(2)}`)
    }
    lines.push('')
  } else {
    lines.push('_No low-score chunks._', '')
  }
  if (includeFooter) {
    lines.push('---', '', '_Generated by OpenTrace Studio_', '')
  }
  return lines.join('\n')
}
